import { NextRequest, NextResponse } from 'next/server'
import { createRepo, pushFiles, getAuthenticatedUser } from '@/lib/github'
import { createProject } from '@/lib/vercel-api'
import { saveAgent, getAgent } from '@/lib/registry'

export const runtime = 'nodejs'

export async function POST(req: NextRequest) {
  const { agentId, repoName }: { agentId: string; repoName: string } = await req.json()

  const agent = getAgent(agentId)
  if (!agent) {
    return NextResponse.json({ error: 'Agent not found' }, { status: 404 })
  }

  try {
    // 1. Get GitHub user
    const ghUser = await getAuthenticatedUser()

    // 2. Create GitHub repo
    const repo = await createRepo(repoName, agent.spec.description)

    // 3. Push agent files
    const ext = agent.spec.format === 'nextjs-api-route' ? 'ts' : 'ts'
    await pushFiles(ghUser.login, repo.name, [
      { path: `agent.${ext}`, content: agent.code },
      {
        path: 'README.md',
        content: `# ${agent.spec.name}\n\n${agent.spec.description}\n\nGenerated by [Agent Prospector](https://github.com/agent-prospector)\n`,
      },
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name: repoName,
            version: '1.0.0',
            type: 'module',
            scripts: { start: 'node agent.js' },
            dependencies: { '@anthropic-ai/sdk': '^0.52.0' },
          },
          null,
          2
        ),
      },
    ])

    const githubUrl = repo.html_url

    // 4. Create Vercel project linked to GitHub repo
    let vercelUrl: string | undefined
    try {
      const project = await createProject(repoName, ghUser.login, repo.name)
      vercelUrl = `https://${project.name}.vercel.app`
    } catch {
      // Vercel linking is best-effort
    }

    // 5. Update agent record
    const updated = {
      ...agent,
      status: 'deployed' as const,
      githubUrl,
      vercelUrl,
      updatedAt: new Date().toISOString(),
    }
    saveAgent(updated)

    return NextResponse.json({ success: true, githubUrl, vercelUrl })
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Deploy failed'
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
