import { NextRequest, NextResponse } from 'next/server'
import { createRepo, pushFiles, getAuthenticatedUser } from '@/lib/github'
import { createProject } from '@/lib/vercel-api'
import { getAgent } from '@/lib/registry'
import { z } from 'zod'

export const runtime = 'nodejs'

const DeploySchema = z.object({
  agentId: z.string(),
  repoName: z.string().min(1).max(100).regex(/^[a-z0-9-]+$/, 'lowercase alphanumeric + hyphens only'),
  // Optional — passed directly from client to avoid cold-start registry loss
  agentCode: z.string().optional(),
  agentDescription: z.string().optional(),
})

export async function POST(req: NextRequest) {
  let body: unknown
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const parsed = DeploySchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })
  }

  const { agentId, repoName, agentCode: inlineCode, agentDescription } = parsed.data

  // Prefer inline code (from client), fall back to server registry
  const agent = getAgent(agentId)
  const code = inlineCode ?? agent?.code
  const description = agentDescription ?? agent?.spec.description ?? ''

  if (!code) {
    return NextResponse.json(
      { error: 'Agent not found. Try regenerating the code.' },
      { status: 404 }
    )
  }

  try {
    const ghUser = await getAuthenticatedUser()
    const repo = await createRepo(repoName, description)

    await pushFiles(ghUser.login, repo.name, [
      { path: 'agent.ts', content: code },
      {
        path: 'README.md',
        content: `# ${repoName}\n\n${description}\n\nGenerated by [Agent Prospector](https://agent-prospector.vercel.app)\n`,
      },
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name: repoName,
            version: '1.0.0',
            type: 'module',
            scripts: { start: 'npx tsx agent.ts' },
            dependencies: {
              '@anthropic-ai/sdk': '^0.52.0',
              tsx: '^4.0.0',
            },
          },
          null,
          2
        ),
      },
    ])

    const githubUrl = repo.html_url
    let vercelUrl: string | undefined

    try {
      const project = await createProject(repoName, ghUser.login, repo.name)
      vercelUrl = `https://${project.name}.vercel.app`
    } catch {
      // Vercel linking requires OAuth connection — best effort
    }

    return NextResponse.json({ success: true, githubUrl, vercelUrl })
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Deploy failed'
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
